version: 2
updates:
  # Enable version updates for npm/pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username" # Replace with your GitHub username
    assignees:
      - "your-github-username" # Replace with your GitHub username
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      # Group React Testing Library packages
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
      # Group Supabase packages
      supabase:
        patterns:
          - "@supabase/*"
      # Group UI component packages
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
      # Group development tools
      dev-tools:
        patterns:
          - "eslint*"
          - "typescript"
          - "prettier"
          - "@types/*"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
